// <auto-generated />
using System;
using InterviewHelper.Web;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InterviewHelper.Web.Migrations
{
    [DbContext(typeof(HumanResourcesContext))]
    [Migration("20220117072007_rename")]
    partial class rename
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InterviewHelper.DAL.Models.Entities.AnswerPart", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AnswerPartJSON")
                        .HasColumnType("text");

                    b.Property<long>("HumanResourceId")
                        .HasColumnType("bigint");

                    b.Property<int>("PartNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HumanResourceId");

                    b.ToTable("AnswerParts");
                });

            modelBuilder.Entity("InterviewHelper.DAL.Models.Entities.HumanResource", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("DateInput")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("HumanResources");
                });

            modelBuilder.Entity("InterviewHelper.DAL.Models.Entities.AnswerPart", b =>
                {
                    b.HasOne("InterviewHelper.DAL.Models.Entities.HumanResource", null)
                        .WithMany("AnswerParts")
                        .HasForeignKey("HumanResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InterviewHelper.DAL.Models.Entities.HumanResource", b =>
                {
                    b.Navigation("AnswerParts");
                });
#pragma warning restore 612, 618
        }
    }
}
